apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-app-config
  namespace: sample-app
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.monitoring.svc.cluster.local:4317"
  OTEL_SERVICE_NAME: "sample-app"
  LOG_LEVEL: "info"